import type { PantryRecipe } from './types';

export const RECIPES: readonly PantryRecipe[] = [
  {
    id: 'pollo-al-limone',
    title: 'Pollo al limone',
    description: 'Bocconcini teneri in una salsa fresca e veloce.',
    category: 'meat',
    durationMinutes: 25,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken_breast', amount: '300 g' },
      { ingredientId: 'lemon', amount: '1' },
      { ingredientId: 'garlic', amount: '1 spicchio' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.' },
    ],
    steps: [
      'Taglia il pollo a bocconcini uniformi.',
      'Rosola aglio e pollo nell’olio caldo.',
      'Aggiungi il succo di limone e cuoci per 10 minuti.',
      'Regola di sale e pepe prima di servire.',
    ],
    tags: ['veloce', 'padella'],
  },
  {
    id: 'straccetti-manzo-rucola',
    title: 'Straccetti di manzo con rucola',
    description: 'Manzo rosolato con rucola fresca e limone.',
    category: 'meat',
    durationMinutes: 20,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'beef_strips', amount: '300 g' },
      { ingredientId: 'arugula', amount: '80 g' },
      { ingredientId: 'lemon', amount: '1/2' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.', optional: true },
    ],
    steps: [
      'Rosola gli straccetti in una padella molto calda.',
      'Sala la carne e aggiungi il succo di limone.',
      'Spegni il fuoco e unisci la rucola fresca.',
      'Completa con olio e pepe prima di servire.',
    ],
    tags: ['veloce', 'padella'],
  },
  {
    id: 'polpette-al-pomodoro',
    title: 'Polpette al pomodoro',
    description: 'Polpette morbide cotte lentamente nella passata.',
    category: 'meat',
    durationMinutes: 40,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredientId: 'ground_beef', amount: '300 g' },
      { ingredientId: 'eggs', amount: '1' },
      { ingredientId: 'breadcrumbs', amount: '40 g' },
      { ingredientId: 'parmesan', amount: '30 g' },
      { ingredientId: 'tomato_sauce', amount: '350 ml' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Impasta carne, uovo, pangrattato, parmigiano e sale.',
      'Forma delle polpette della stessa dimensione.',
      'Rosola le polpette nell’olio su tutti i lati.',
      'Aggiungi la passata e cuoci coperto per 25 minuti.',
    ],
    tags: ['tradizionale', 'sugo'],
  },
  {
    id: 'tacchino-peperoni',
    title: 'Tacchino con peperoni',
    description: 'Un secondo colorato preparato tutto in padella.',
    category: 'meat',
    durationMinutes: 30,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'turkey_breast', amount: '300 g' },
      { ingredientId: 'bell_peppers', amount: '2' },
      { ingredientId: 'onion', amount: '1/2' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.', optional: true },
    ],
    steps: [
      'Affetta il tacchino, i peperoni e la cipolla.',
      'Ammorbidisci cipolla e peperoni nell’olio caldo.',
      'Aggiungi il tacchino e cuoci per 12 minuti.',
      'Regola di sale e pepe prima di servire.',
    ],
    tags: ['padella', 'verdure'],
  },
  {
    id: 'pasta-tonno-pomodoro',
    title: 'Pasta tonno e pomodoro',
    description: 'Un primo rapido con ingredienti da dispensa.',
    category: 'fish',
    durationMinutes: 20,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'pasta', amount: '180 g' },
      { ingredientId: 'tuna', amount: '120 g' },
      { ingredientId: 'tomato_sauce', amount: '250 ml' },
      { ingredientId: 'garlic', amount: '1 spicchio', optional: true },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Cuoci la pasta in acqua salata seguendo i tempi indicati.',
      'Scalda la passata nell’olio con l’eventuale aglio.',
      'Unisci il tonno sgocciolato e mescola delicatamente.',
      'Scola la pasta e mantecala nel sugo preparato.',
    ],
    tags: ['veloce', 'pasta'],
  },
  {
    id: 'merluzzo-olive-pomodorini',
    title: 'Merluzzo con olive e pomodorini',
    description: 'Filetti delicati con un condimento mediterraneo.',
    category: 'fish',
    durationMinutes: 30,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'cod', amount: '300 g' },
      { ingredientId: 'cherry_tomatoes', amount: '200 g' },
      { ingredientId: 'olives', amount: '60 g' },
      { ingredientId: 'garlic', amount: '1 spicchio' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'parsley', amount: '1 ciuffo', optional: true },
    ],
    steps: [
      'Rosola lo spicchio d’aglio nell’olio caldo.',
      'Aggiungi i pomodorini tagliati e le olive.',
      'Adagia il merluzzo nella padella e copri.',
      'Cuoci per 15 minuti e completa con prezzemolo.',
    ],
    tags: ['mediterranea', 'padella'],
  },
  {
    id: 'salmone-al-limone',
    title: 'Salmone al limone',
    description: 'Salmone dorato con limone e prezzemolo.',
    category: 'fish',
    durationMinutes: 20,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'salmon', amount: '300 g' },
      { ingredientId: 'lemon', amount: '1' },
      { ingredientId: 'parsley', amount: '1 ciuffo' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.' },
    ],
    steps: [
      'Scalda l’olio in una padella antiaderente.',
      'Cuoci il salmone per quattro minuti su ogni lato.',
      'Aggiungi il succo di limone nella padella.',
      'Condisci con sale, pepe e prezzemolo tritato.',
    ],
    tags: ['veloce', 'padella'],
  },
  {
    id: 'insalata-ceci-tonno',
    title: 'Insalata di ceci e tonno',
    description: 'Un piatto unico fresco, saziante e senza cottura.',
    category: 'fish',
    durationMinutes: 10,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'chickpeas', amount: '240 g' },
      { ingredientId: 'tuna', amount: '120 g' },
      { ingredientId: 'tomato', amount: '2' },
      { ingredientId: 'onion', amount: '1/4' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'lemon', amount: '1/2' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'parsley', amount: '1 ciuffo', optional: true },
    ],
    steps: [
      'Scola con cura i ceci e il tonno.',
      'Taglia i pomodori e affetta finemente la cipolla.',
      'Riunisci tutti gli ingredienti in una ciotola.',
      'Condisci con olio, limone e sale prima di servire.',
    ],
    tags: ['senza cottura', 'piatto unico'],
  },
  {
    id: 'frittata-zucchine',
    title: 'Frittata di zucchine',
    description: 'Una frittata semplice, morbida e ricca di verdure.',
    category: 'eggs',
    durationMinutes: 25,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'eggs', amount: '4' },
      { ingredientId: 'zucchini', amount: '2' },
      { ingredientId: 'parmesan', amount: '30 g' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.', optional: true },
    ],
    steps: [
      'Affetta le zucchine e rosolale nell’olio.',
      'Sbatti le uova con parmigiano e sale.',
      'Versa il composto sulle zucchine in padella.',
      'Cuoci coperto e gira la frittata a metà cottura.',
    ],
    tags: ['padella', 'vegetariana'],
  },
  {
    id: 'uova-al-pomodoro',
    title: 'Uova al pomodoro',
    description: 'Uova cotte direttamente in un sugo saporito.',
    category: 'eggs',
    durationMinutes: 20,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'eggs', amount: '4' },
      { ingredientId: 'tomato_sauce', amount: '300 ml' },
      { ingredientId: 'garlic', amount: '1 spicchio' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.', optional: true },
    ],
    steps: [
      'Scalda aglio e passata nell’olio per cinque minuti.',
      'Crea quattro piccoli incavi nella salsa.',
      'Rompi le uova negli incavi senza muoverle.',
      'Copri e cuoci finché gli albumi risultano sodi.',
    ],
    tags: ['padella', 'vegetariana'],
  },
  {
    id: 'omelette-spinaci',
    title: 'Omelette agli spinaci',
    description: 'Omelette cremosa con spinaci e parmigiano.',
    category: 'eggs',
    durationMinutes: 20,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'eggs', amount: '4' },
      { ingredientId: 'spinach', amount: '180 g' },
      { ingredientId: 'milk', amount: '2 cucchiai' },
      { ingredientId: 'parmesan', amount: '25 g' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Salta gli spinaci in padella finché appassiscono.',
      'Sbatti uova, latte, parmigiano e sale.',
      'Versa il composto nella padella calda.',
      'Ripiega l’omelette quando il centro è ancora morbido.',
    ],
    tags: ['veloce', 'vegetariana'],
  },
  {
    id: 'carbonara-semplice',
    title: 'Carbonara semplice',
    description: 'Una versione casalinga e immediata della carbonara.',
    category: 'eggs',
    durationMinutes: 25,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredientId: 'pasta', amount: '180 g' },
      { ingredientId: 'eggs', amount: '2' },
      { ingredientId: 'pancetta', amount: '100 g' },
      { ingredientId: 'parmesan', amount: '50 g' },
      { ingredientId: 'black_pepper', amount: 'q.b.' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Cuoci la pasta in acqua moderatamente salata.',
      'Rosola la pancetta finché diventa croccante.',
      'Mescola le uova con parmigiano e pepe.',
      'Manteca fuori dal fuoco con poca acqua di cottura.',
    ],
    tags: ['pasta', 'tradizionale'],
  },
  {
    id: 'pasta-e-ceci',
    title: 'Pasta e ceci',
    description: 'Pasta cremosa e confortante cotta in una sola pentola.',
    category: 'legumes',
    durationMinutes: 30,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'pasta', amount: '160 g' },
      { ingredientId: 'chickpeas', amount: '240 g' },
      { ingredientId: 'tomato_sauce', amount: '150 ml' },
      { ingredientId: 'garlic', amount: '1 spicchio' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'water', amount: '400 ml' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Rosola lo spicchio d’aglio nell’olio.',
      'Unisci ceci, passata e acqua nella pentola.',
      'Porta a bollore e aggiungi la pasta.',
      'Cuoci mescolando fino a ottenere una consistenza cremosa.',
    ],
    tags: ['piatto unico', 'tradizionale'],
  },
  {
    id: 'lenticchie-in-umido',
    title: 'Lenticchie in umido',
    description: 'Lenticchie morbide con un soffritto essenziale.',
    category: 'legumes',
    durationMinutes: 40,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'lentils', amount: '240 g' },
      { ingredientId: 'tomato_sauce', amount: '200 ml' },
      { ingredientId: 'carrots', amount: '1' },
      { ingredientId: 'celery', amount: '1 costa' },
      { ingredientId: 'onion', amount: '1/2' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'water', amount: '300 ml' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Trita finemente carota, sedano e cipolla.',
      'Soffriggi le verdure nell’olio a fuoco dolce.',
      'Unisci lenticchie, passata e acqua.',
      'Cuoci per 25 minuti e regola di sale.',
    ],
    tags: ['vegana', 'pentola'],
  },
  {
    id: 'insalata-fagioli-cipolla',
    title: 'Insalata di fagioli e cipolla',
    description: 'Fagioli freschi e saporiti con pomodoro e limone.',
    category: 'legumes',
    durationMinutes: 10,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'cannellini_beans', amount: '240 g' },
      { ingredientId: 'onion', amount: '1/4' },
      { ingredientId: 'tomato', amount: '2' },
      { ingredientId: 'parsley', amount: '1 ciuffo' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'lemon', amount: '1/2' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Scola e risciacqua i fagioli cannellini.',
      'Affetta la cipolla e taglia i pomodori.',
      'Riunisci gli ingredienti in una ciotola capiente.',
      'Condisci con prezzemolo, olio, limone e sale.',
    ],
    tags: ['senza cottura', 'vegana'],
  },
  {
    id: 'burger-di-ceci',
    title: 'Burger di ceci',
    description: 'Burger dorati fuori e morbidi dentro.',
    category: 'legumes',
    durationMinutes: 30,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredientId: 'chickpeas', amount: '240 g' },
      { ingredientId: 'breadcrumbs', amount: '50 g' },
      { ingredientId: 'eggs', amount: '1' },
      { ingredientId: 'onion', amount: '1/4' },
      { ingredientId: 'parsley', amount: '1 ciuffo' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'black_pepper', amount: 'q.b.', optional: true },
    ],
    steps: [
      'Schiaccia i ceci fino a ottenere un composto grossolano.',
      'Impasta con uovo, pangrattato, cipolla e prezzemolo.',
      'Forma quattro burger compatti con le mani.',
      'Cuoci nell’olio per quattro minuti su ogni lato.',
    ],
    tags: ['padella', 'vegetariana'],
  },
  {
    id: 'pasta-alla-norma',
    title: 'Pasta alla norma',
    description: 'Pasta al pomodoro con melanzane e basilico.',
    category: 'vegetables',
    durationMinutes: 35,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredientId: 'pasta', amount: '180 g' },
      { ingredientId: 'eggplant', amount: '1' },
      { ingredientId: 'tomato_sauce', amount: '300 ml' },
      { ingredientId: 'basil', amount: '6 foglie' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'parmesan', amount: '30 g', optional: true },
    ],
    steps: [
      'Taglia la melanzana a cubetti e rosolala.',
      'Aggiungi la passata e cuoci per dieci minuti.',
      'Cuoci la pasta in acqua salata e scolala.',
      'Manteca nel sugo e completa con basilico.',
    ],
    tags: ['pasta', 'vegetariana'],
  },
  {
    id: 'couscous-verdure',
    title: 'Cous cous alle verdure',
    description: 'Cous cous leggero con ortaggi colorati.',
    category: 'vegetables',
    durationMinutes: 25,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'couscous', amount: '160 g' },
      { ingredientId: 'zucchini', amount: '1' },
      { ingredientId: 'bell_peppers', amount: '1' },
      { ingredientId: 'peas', amount: '100 g' },
      { ingredientId: 'water', amount: '180 ml' },
      { ingredientId: 'olive_oil', amount: '2 cucchiai' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Taglia le verdure e saltale in padella.',
      'Versa l’acqua bollente salata sul cous cous.',
      'Lascia riposare e sgrana con l’olio.',
      'Unisci le verdure e i piselli al cous cous.',
    ],
    tags: ['veloce', 'vegana'],
  },
  {
    id: 'zuppa-rustica-verdure',
    title: 'Zuppa rustica di verdure',
    description: 'Una zuppa semplice per usare le verdure disponibili.',
    category: 'vegetables',
    durationMinutes: 45,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'potatoes', amount: '2' },
      { ingredientId: 'carrots', amount: '2' },
      { ingredientId: 'celery', amount: '1 costa' },
      { ingredientId: 'zucchini', amount: '1' },
      { ingredientId: 'onion', amount: '1/2' },
      { ingredientId: 'tomato', amount: '2' },
      { ingredientId: 'water', amount: '800 ml' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
    ],
    steps: [
      'Lava e taglia tutte le verdure a pezzi regolari.',
      'Rosola la cipolla nell’olio a fuoco dolce.',
      'Aggiungi le verdure e copri con l’acqua.',
      'Cuoci per 35 minuti e regola di sale.',
    ],
    tags: ['pentola', 'vegana'],
  },
  {
    id: 'riso-zucchine-piselli',
    title: 'Riso con zucchine e piselli',
    description: 'Riso morbido con zucchine e piselli.',
    category: 'vegetables',
    durationMinutes: 30,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredientId: 'rice', amount: '160 g' },
      { ingredientId: 'zucchini', amount: '2' },
      { ingredientId: 'peas', amount: '120 g' },
      { ingredientId: 'onion', amount: '1/2' },
      { ingredientId: 'water', amount: '500 ml' },
      { ingredientId: 'olive_oil', amount: '1 cucchiaio' },
      { ingredientId: 'salt', amount: 'q.b.' },
      { ingredientId: 'parmesan', amount: '30 g', optional: true },
    ],
    steps: [
      'Rosola la cipolla tritata nell’olio.',
      'Aggiungi il riso e le zucchine tagliate.',
      'Versa l’acqua poco alla volta durante la cottura.',
      'Unisci i piselli a metà cottura e completa a piacere.',
    ],
    tags: ['pentola', 'vegetariana'],
  },
];

export const getRecipeById = (id: string): PantryRecipe | undefined =>
  RECIPES.find((recipe) => recipe.id === id);
